/*
 * This file is generated by jOOQ.
 */
package com.melon.mysql.generatedclasses.tables.records;


import com.melon.mysql.generatedclasses.tables.People;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PeopleRecord extends UpdatableRecordImpl<PeopleRecord> implements Record4<Integer, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>jooq_demo.people.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>jooq_demo.people.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jooq_demo.people.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jooq_demo.people.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jooq_demo.people.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>jooq_demo.people.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>jooq_demo.people.gender</code>.
     */
    public void setGender(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>jooq_demo.people.gender</code>.
     */
    public String getGender() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return People.PEOPLE.ID;
    }

    @Override
    public Field<String> field2() {
        return People.PEOPLE.NAME;
    }

    @Override
    public Field<String> field3() {
        return People.PEOPLE.EMAIL;
    }

    @Override
    public Field<String> field4() {
        return People.PEOPLE.GENDER;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getEmail();
    }

    @Override
    public String component4() {
        return getGender();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getEmail();
    }

    @Override
    public String value4() {
        return getGender();
    }

    @Override
    public PeopleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PeopleRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public PeopleRecord value3(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public PeopleRecord value4(String value) {
        setGender(value);
        return this;
    }

    @Override
    public PeopleRecord values(Integer value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PeopleRecord
     */
    public PeopleRecord() {
        super(People.PEOPLE);
    }

    /**
     * Create a detached, initialised PeopleRecord
     */
    public PeopleRecord(Integer id, String name, String email, String gender) {
        super(People.PEOPLE);

        setId(id);
        setName(name);
        setEmail(email);
        setGender(gender);
        resetChangedOnNotNull();
    }
}
