/*
 * This file is generated by jOOQ.
 */
package com.melon.mysql.generatedclasses;


import com.melon.mysql.generatedclasses.tables.People;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in jooq_demo.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PEOPLE_IDX_PEOPLE_ID = Internal.createIndex(DSL.name("idx_people_id"), People.PEOPLE, new OrderField[] { People.PEOPLE.ID }, false);
}
