/*
 * This file is generated by jOOQ.
 */
package com.melon.mysql.generatedclasses;


import com.melon.mysql.generatedclasses.tables.People;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqDemo extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>jooq_demo</code>
     */
    public static final JooqDemo JOOQ_DEMO = new JooqDemo();

    /**
     * The table <code>jooq_demo.people</code>.
     */
    public final People PEOPLE = People.PEOPLE;

    /**
     * No further instances allowed
     */
    private JooqDemo() {
        super("jooq_demo", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            People.PEOPLE
        );
    }
}
