/*
 * This file is generated by jOOQ.
 */
package com.melon.mysql.generatedclasses;


import com.melon.mysql.generatedclasses.tables.People;
import com.melon.mysql.generatedclasses.tables.records.PeopleRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * jooq_demo.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PeopleRecord> KEY_PEOPLE_PRIMARY = Internal.createUniqueKey(People.PEOPLE, DSL.name("KEY_people_PRIMARY"), new TableField[] { People.PEOPLE.ID }, true);
}
