/*
 * This file is generated by jOOQ.
 */
package com.melon.mysql.generatedclasses;


import com.melon.mysql.generatedclasses.tables.People;


/**
 * Convenience access to all tables in jooq_demo.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq_demo.people</code>.
     */
    public static final People PEOPLE = People.PEOPLE;
}
